const reasons = [
    // --- BLOQUE 1: PERSONALIDAD Y ESENCIA ---
    "Por la bondad genuina que hay en tu corazón.",
    "Por tu capacidad de ver el lado positivo incluso en los días grises.",
    "Por la inteligencia con la que resuelves cualquier problema.",
    "Por tu paciencia infinita cuando me explicas algo.",
    "Por la valentía con la que enfrentas tus miedos.",
    "Por esa chispa de locura que hace que la vida sea divertida.",
    "Por tu honestidad, aunque a veces duela.",
    "Por la forma en que cuidas a las personas que amas.",
    "Por tu ambición y las ganas que tienes de comerte el mundo.",
    "Por tu humildad a pesar de todo lo que vales.",
    "Por esa primera vez que nuestras miradas se cruzaron.",
    "Por la forma en que me tomas la mano cuando caminamos.",
    "Por los silencios cómodos que compartimos.",
    "Por nuestras charlas profundas de madrugada.",
    "Por cómo me haces reír cuando estoy a punto de llorar.",
    "Por cada café o comida que hemos compartido.",
    "Por los viajes que hemos hecho y los que vendrán.",
    "Por el apoyo que me das en mis proyectos más locos.",
    "Por cómo respetas mi espacio y mis tiempos.",
    "Por los abrazos que me reinician el alma.",
    "Por el brillo de tus ojos cuando hablas de algo que te apasiona.",
    "Por esa pequeña marca o lunar que solo yo conozco.",
    "Por la suavidad de tu piel.",
    "Por tu aroma, que se queda en mi ropa y me hace recordarte.",
    "Por la forma en que acomodas tu cabello tras la oreja.",
    "Por tu sonrisa, que ilumina cualquier lugar oscuro.",
    "Por la calidez de tus besos.",
    "Por cómo encajas perfectamente en mis brazos.",
    "Por tus gestos cuando estás concentrada.",
    "Por la paz que transmite tu rostro cuando duermes.",
    "Por creer en mí cuando ni yo mismo lo hacía.",
    "Por ser mi lugar seguro en este mundo caótico.",
    "Por los planes que construimos juntos.",
    "Por querer ser una mejor versión de ti misma cada día.",
    "Por cómo me inspiras a ser mejor persona.",
    "Por defender lo nuestro ante cualquier adversidad.",
    "Por la confianza ciega que tenemos el uno en el otro.",
    "Por perdonar mis errores y ayudarme a aprender de ellos.",
    "Por ser mi mejor amiga además de mi pareja.",
    "Por el simple hecho de existir y estar en mi vida.",
    "Por cómo preparas el café (o tu comida favorita).",
    "Por tus gustos musicales tan especiales.",
    "Por las películas que vemos aunque te quedes dormida.",
    "Por tus mensajes de 'buenos días' que me alegran la jornada.",
    "Por cómo te llevas con mi familia y amigos.",
    "Por tu estilo único de vestir.",
    "Por las canciones que me dedicas.",
    "Por los memes que me envías para hacerme reír.",
    "Por cómo te preocupas de que haya llegado bien a casa.",
    "Por tu forma de bailar cuando nadie te ve.",

    // --- BLOQUE 2: DETALLES ÚNICOS (101-200) ---
    "Por la forma en que tus ojos brillan cuando hablas de tus sueños.",
    "Por ese bailecito que haces cuando comes algo que te gusta mucho.",
    "Por cómo te muerdes el labio cuando estás concentrada en algo difícil.",
    "Por la manera en que buscas mi mano cuando hay mucha gente alrededor.",
    "Por el sonido de tu risa, que es mi melodía favorita en el mundo.",
    "Por cómo arrugas la nariz cuando algo te da gracia o ternura.",
    "Por la paz que transmites cuando duermes profundamente.",
    "Por la forma en que me miras cuando crees que no me doy cuenta.",
    "Por cómo te acomodas el cabello detrás de la oreja con tanta elegancia.",
    "Por el tono de tu voz cuando me dices 'te quiero' bajito.",
    "Por cómo saludas con la mano cuando te vas, como si fuera la primera vez.",
    "Por la forma en que tus manos encajan perfectamente con las mías.",
    "Por cómo te ves con mi ropa, aunque te quede gigante.",
    "Por tus abrazos largos, esos que parece que detienen el tiempo.",
    "Por la forma en que caminas, siempre con paso firme y seguro.",
    "Por cómo cierras los ojos cuando nos besamos.",
    "Por ese aroma tan tuyo que se queda impregnado en mis almohadas.",
    "Por la calidez de tu piel cuando nos acurrucamos.",
    "Por tus gestos exagerados cuando me cuentas una historia emocionante.",
    "Por la forma en que me corriges cuando me equivoco, siempre con cariño.",
    "Por la valentía inmensa con la que enfrentas cada desafío.",
    "Por tu capacidad de perdonar y volver a empezar con el corazón limpio.",
    "Por la empatía que sientes hacia el dolor de los demás.",
    "Por tu inteligencia, que no deja de sorprenderme y enseñarme cosas nuevas.",
    "Por la pasión que le pones a cada pequeño proyecto que emprendes.",
    "Por tu honestidad brutal, incluso cuando es difícil de decir.",
    "Por la lealtad inquebrantable que le tienes a tus principios.",
    "Por tu humildad, a pesar de ser la persona más increíble que conozco.",
    "Por esa curiosidad de niña que te hace querer descubrir el mundo.",
    "Por la resiliencia que demuestras cuando la vida se pone difícil.",
    "Por tu sentido de la justicia y cómo defiendes a los que no tienen voz.",
    "Por la forma en que cuidas tu mundo interior y tu paz mental.",
    "Por tu capacidad de reírte de ti misma sin miedos.",
    "Por la seguridad que proyectas, aunque por dentro tengas dudas.",
    "Por tu generosidad sin límites, siempre dispuesta a dar una mano.",
    "Por la madurez con la que manejas nuestros momentos de desacuerdo.",
    "Por tu creatividad para encontrar soluciones donde otros ven problemas.",
    "Por la luz que emanas, que es capaz de iluminar mi día más oscuro.",
    "Por tu disciplina para alcanzar las metas que te propones.",
    "Por la dulzura que guardas para los momentos en que más la necesito.",
    "Por cómo sabes exactamente qué estoy pensando sin que diga una palabra.",
    "Por la forma en que respetas mi libertad y mis espacios personales.",
    "Por ser mi mayor apoyo en mis decisiones más arriesgadas.",
    "Por los 'chistes internos' que solo nosotros dos entendemos.",
    "Por cómo me inspiras a ser una mejor versión de mí mismo cada día.",
    "Por la confianza absoluta que puedo depositar en ti.",
    "Por cómo me haces sentir seguro y amado con un solo mensaje.",
    "Por las conversaciones profundas que tenemos a las tres de la mañana.",
    "Por la forma en que nos complementamos, como dos piezas exactas.",
    "Por creer en mi potencial incluso cuando yo mismo dudo.",
    "Por el respeto mutuo que es la base de todo lo que construimos.",
    "Por cómo celebramos juntos mis triunfos como si fueran tuyos.",
    "Por ser el refugio donde siempre quiero volver después de un día duro.",
    "Por la paciencia que me tienes cuando me pongo difícil de aguantar.",
    "Por cómo planeamos nuestro futuro con tanta ilusión y detalle.",
    "Por la forma en que me haces reír hasta que me duele la panza.",
    "Por los silencios cómodos, donde no hace falta decir nada.",
    "Por cómo cuidas nuestra relación como el tesoro más grande.",
    "Por el apoyo incondicional que le das a mis sueños más locos.",
    "Por la forma en que me haces sentir que somos un equipo invencible.",
    "Por cómo te ves de hermosa recién despierta y despeinada.",
    "Por tu gusto musical y las canciones que me descubres.",
    "Por la forma en que preparas el café (o tu comida favorita).",
    "Por cómo te preocupas de que descanse bien y coma sano.",
    "Por los memes que me envías solo para hacerme el día más ligero.",
    "Por cómo te llevas con las personas que son importantes para mí.",
    "Por tu estilo único, que te hace destacar en cualquier lugar.",
    "Por cómo organizas tus cosas con ese orden (o caos) tan tuyo.",
    "Por la alegría que pones cuando llega el fin de semana para vernos.",
    "Por cómo te quedas dormida en mi hombro mientras vemos una película.",
    "Por los mensajes de 'buenos días' que son lo primero que quiero leer.",
    "Por cómo te emocionas con los pequeños detalles de la naturaleza.",
    "Por la forma en que tratas a los animales con tanta ternura.",
    "Por tu habilidad para encontrar belleza en las cosas más simples.",
    "Por cómo hueles después de un día largo de trabajo, a esfuerzo y vida.",
    "Por la forma en que me pides perdón cuando sabes que te equivocaste.",
    "Por cómo me escuchas con total atención cuando te cuento mis problemas.",
    "Por las notas que me dejas o los recordatorios cariñosos.",
    "Por cómo te esfuerzas por entender mis pasatiempos, aunque no sean los tuyos.",
    "Por la forma en que iluminas la casa con solo entrar por la puerta.",
    "Porque contigo he aprendido lo que realmente significa amar sin condiciones.",
    "Porque me has enseñado que la vulnerabilidad es una forma de valentía.",
    "Porque a tu lado el mundo parece un lugar mucho menos aterrador.",
    "Porque eres la primera persona en la que pienso cuando tengo una buena noticia.",
    "Porque me has demostrado que el amor real se construye en los detalles.",
    "Porque tu sola existencia hace que el planeta sea un lugar mejor.",
    "Porque no tratas de cambiarme, sino que me ayudas a crecer.",
    "Porque eres mi mejor amiga, mi amante y mi confidente.",
    "Porque cada día que paso contigo es un regalo que no quiero desperciar.",
    "Porque me encanta la persona en la que me convierto cuando estoy contigo.",
    "Porque eres mi hogar, sin importar en qué lugar del mundo estemos.",
    "Porque tu amor es el ancla que me mantiene firme en la tormenta.",
    "Porque compartes tus miedos conmigo, y eso me hace sentir honrado.",
    "Porque eres la pieza que no sabía que me faltaba.",
    "Porque me aceptas con todas mis sombras y cicatrices.",
    "Porque tu bondad no tiene límites ni espera nada a cambio.",
    "Porque me das la libertad de ser yo mismo al 100%.",
    "Porque eres la razón detrás de mis sonrisas más sinceras.",
    "Porque nuestro amor es fácil, natural y simplemente fluye.",
    "Porque te amo por quien eres, pero sobre todo, por cómo me haces sentir."
];

// --- LÓGICA DE LA PÁGINA ---
const listContainer = document.getElementById('reasons-list');
const searchInput = document.getElementById('search');

function displayReasons(filter = '') {
    listContainer.innerHTML = '';
    // Filtrar razones
    const filteredReasons = reasons.filter(r => r.toLowerCase().includes(filter.toLowerCase()));
    
    filteredReasons.forEach((reason, index) => {
        const card = document.createElement('div');
        card.className = 'reason-card';
        // Encontrar el índice original para mantener el número correcto
        const originalIndex = reasons.indexOf(reason);
        card.innerHTML = `<span class="number">#${originalIndex + 1}</span> ${reason}`;
        listContainer.appendChild(card);
    });
}

// Escuchar el buscador
searchInput.addEventListener('input', (e) => displayReasons(e.target.value));

// Carga inicial
displayReasons();
  
